# WRAPPER, sets parameters then calls Microsoft RS.EXE 

# PATH FOR RS.EXE
# DEFAULT FOR 2016 AND EARLIER:
# C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\rs.exe
# DEFAULT FOR 2017 AND LATER INCLUDING PBIRS: 
# C:\Program Files\Microsoft SQL Server Reporting Services\Shared Tools\RS.exe
# DEFAULT FOR POWER BI REPORT SERVER:
# C:\Program Files\Microsoft Power BI Report Server\Shared Tools\RS.exe
$RSEXE_Path = "C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\rs.exe"

# PATH FOR MIGRATION SCRIPT - POINT THIS TO THE LOCATION YOU DOWNLOADED YOUR SCRIPT TO!
# DEFAULT/SAMPLE MIGRATION SCRIPT AVAILABLE HERE: 
# https://github.com/microsoft/sql-server-samples/blob/master/samples/features/reporting-services/ssrs-migration-rss/ssrs_migration.rss
$MIGRATION_SCRIPT_PATH = "C:\Users\PEDRO\Desktop\ssrs_migration.rss"

# SOURCE AND DESTINATION URLs SHOULD POINT TO YOUR /REPORTSERVER PATH
# NOTE: YOU MUST BE ABLE TO CONNECT TO BOTH OF THESE URLs FROM THE MACHINE LAUNCHING THIS SCRIPT
$SOURCE_URL = "https://source-server.com/ReportServer"
$DESTINATION_URL = "https://destination-server.com/ReportServer"

# CREDENTIALS TO USE TO LOGIN TO SOURCE REPORT SERVER
$SOURCE_USER = "BIWIN\PEDRO"
$SOURCE_PW = "MyPassword123!"

# CREDENTIALS TO USE TO LOGIN TO DESTINATION REPORT SERVER
$DESTINATION_USER = "BIWIN\PEDRO"
$DESINATION_PW = "MyPassword123!"

# FOR THE ROOT PATH, ENTER "/" FOR PATH
# IMPORTANT NOTE: THE DESTINATION FOLDER MUST ALREADY EXIST! THE SCRIPT WILL NOT AUTO-CREATE THE FOLDER!
$SOURCE_FOLDER = "/"
$DESTINATION_FOLDER = "/"

# SET SECURITY TO FALSE TO INHERIT PERMISSIONS FROM DESTINATION SERVER
# SET SECURITY TO TRUE TO MIGRATE PERMISSIONS FROM SOURCE SERVER
$SECURITY = "False"

& $RSEXE_Path -i $MIGRATION_SCRIPT_PATH `
-e Mgmt2010 `
-s $SOURCE_URL `
-v f="$SOURCE_FOLDER" `
-v ts="$DESTINATION_URL" `
-v tf="$DESTINATION_FOLDER" `
-v security="$SECURITY" `
-u $SOURCE_USER `
-p $SOURCE_PW `
-v tu="$DESTINATION_USER" `
-v tp="$DESINATION_PW"
